# mysql-simple.yaml: Simple MySQL Deployment
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc # CRITICAL: Matches the name your application is looking for
  namespace: sfs-assessment
spec:
  selector:
    app: mysql-sfs
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sfs-assessment
spec:
  selector:
    matchLabels:
      app: mysql-sfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-sfs
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 # Official stable image
        ports:
        - containerPort: 3306
        env:
          # Use the Secret 'sfs-db-credentials' for the root password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sfs-db-credentials 
                key: SPRING_DATASOURCE_PASSWORD
          # CRITICAL: Ensures the 'sfs' database exists on startup
          - name: MYSQL_DATABASE
            value: sfs
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"